version: "3.8"

services:
  mongodb-patient:
    restart: unless-stopped
    image: mongo:latest
    container_name: mongodb-patient
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGOADMIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGOPASS}
    networks:
      - backend
    ports:
      - "27018:27017"
    volumes:
      - mongo-patient:/data/db

  patient:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patient
    environment:
      - MONGOURL=${MONGOURL}
      - PORT=${PORT}
      - NODE_ENV=development
      - API_PREFIX=${API_PREFIX}
      - KAFKA_HOST=${KAFKA_HOST}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb-patient
    networks:
      - backend
    ports:
      - "3006:3006"

volumes:
  mongo-patient:

networks:
  backend:
    driver: bridge