apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: patient-svc
  name: patient-svc
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3006
      targetPort: 3006
  selector:
    io.kompose.service: patient-svc
