apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: patient-svc
  name: patient-svc
spec:
  ports:
    - name: "3006"
      port: 3006
      targetPort: 3006
  selector:
    io.kompose.service: patient-svc
